### ISSUE TITLE
Problems if initialPage is not 0, have to scroll a little to trigger the NotificationListener

### ISSUE THREAD

**Issue by vmihalachi** [FlutterRocks/page-transformer#7]
Hi, thank you for your library! 
But I think the page transformer doesn't work well if the initial page is not zero. 
Scrolling a little triggers the NotificationListener and then everything is fine. 

Here are some screenshots.

<img width="420" alt="schermata 2018-10-13 alle 11 58 53" src="https://user-images.githubusercontent.com/956257/46904113-af5df780-cedf-11e8-9ff1-83d3acd3b155.png">
<img width="432" alt="schermata 2018-10-13 alle 11 59 05" src="https://user-images.githubusercontent.com/956257/46904114-b258e800-cedf-11e8-9dc6-bfb0047b95e4.png">

**Comment by manangatangy** [comment]
This issue will probably be fixed by https://github.com/roughike/page-transformer/pull/8
I'm not sure if roughike is still active on this repo, so you may want to patch your own copy with this 3 line fix.

**Comment by vishalvishvakarma1111** [comment]
i am getting this error in flutter 2.5 
LateInitializationError: Field '_visibilityResolver@56419319' has not been initialized.
can you help me out
